version: "3"
services:
  node:
    container_name: node
    image: node
    build: ./server
    restart: always
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    depends_on:
      - node
