version: "3"
services:
  main:
    container_name: main
    image: node
    build: ./server
    environment:
      - PORT=4000
    restart: always
  sub:
    container_name: sub
    image: node
    build: ./server
    environment:
      - PORT=4001
    restart: always

  checker:
    container_name: checker
    image: checker
    build: ./checker
    environment:
      - PORT=4002
    restart: always

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    depends_on:
      - main
      - sub
