version: "3"
services:
  node:
    container_name: node
    build:
      # velog directory를 root로 사용
      context: ./server
      # ./velog/Dockerfile을 사용해서 build
      dockerfile: Dockerfile
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    depends_on:
      - node
