version: "3"
services:
  # nginx:
  #   image: "nginx:alpine"
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - node
  node:
    container_name: "node"
    build:
      # velog directory를 root로 사용
      context: ./server
      # ./velog/Dockerfile을 사용해서 build
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
